// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPath() {
  return window['go']['main']['App']['GetPath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OrganizeDir(arg1, arg2) {
  return window['go']['main']['App']['OrganizeDir'](arg1, arg2);
}
