// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OnFileDrop():Promise<string>;

export function OrganizeDir(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SelectFolder():Promise<string>;
